/**
 * 内置模板数据定义
 * 从 templateService.ts 拆出，仅包含内置模板数据。
 *
 * i18n 约定（与「模板直接持 key」的设计一致）：
 * 下面所有可翻译字段（name / description / tags / 列 comment / 索引 comment）
 * 一律存放 **i18n key**（如 `db.tplColPriId`），而非中文字面量；展示前由
 * `TemplateService.localizeTemplate()` 统一 `t(key)` 翻译。
 *
 * 这样做的目的是消除历史上的「中文串 → key」反查表（COMMENT_I18N）：
 * 反查表以中文字面量为键，一旦数据里的中文改动就会静默失配、退回显示原始中文，
 * 且无法覆盖未登记的注释（如字典/审计表列、全部索引注释），在非中文语言下中英混排。
 * 改为直接持 key 后，模板即自描述，新增模板只需补数据与对应 i18n 词条，无需回填任何映射表。
 */

import type { TableTemplate } from '../../types/schema';

/** 内置模板数据（可翻译字段均为 i18n key，需经 localizeTemplate 后方可展示） */
export const builtinTemplateData: TableTemplate[] = [
    {
      id: 'user_table',
      name: 'db.tplUserName',
      description: 'db.tplUserDesc',
      category: 'user',
      tags: ['db.tplTagUser', 'db.tplTagBasic', 'db.tplTagAuth'],
      usageCount: 0,
      createdAt: Date.now(),
      columns: [
        {
          name: 'id',
          type: 'bigint',
          length: '20',
          notNull: true,
          isPrimaryKey: true,
          autoIncrement: true,
          comment: 'db.tplColPriId',
        },
        {
          name: 'username',
          type: 'varchar',
          length: '50',
          notNull: true,
          comment: 'db.tplColUsername',
        },
        {
          name: 'email',
          type: 'varchar',
          length: '100',
          notNull: false,
          comment: 'db.tplColEmail',
        },
        {
          name: 'phone',
          type: 'varchar',
          length: '20',
          notNull: false,
          comment: 'db.tplColPhone',
        },
        {
          name: 'password_hash',
          type: 'varchar',
          length: '255',
          notNull: true,
          comment: 'db.tplColPwdHash',
        },
        {
          name: 'avatar_url',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColAvatar',
        },
        {
          name: 'status',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '1',
          comment: 'db.tplColStatus',
        },
        {
          name: 'last_login_time',
          type: 'datetime',
          notNull: false,
          comment: 'db.tplColLastLogin',
        },
        {
          name: 'creator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColCreatorId',
        },
        {
          name: 'creator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColCreator',
        },
        {
          name: 'create_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColCreateTime',
        },
        {
          name: 'updator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColUpdatorId',
        },
        {
          name: 'updator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColUpdator',
        },
        {
          name: 'update_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColUpdateTime',
        },
        {
          name: 'is_deleted',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '0',
          comment: 'db.tplColIsDeleted',
        },
      ],
      indexes: [
        {
          name: 'uk_username',
          columns: [{ name: 'username' }],
          unique: true,
          type: 'BTREE',
          comment: 'db.tplIdxUsernameUnique',
        },
        {
          name: 'idx_email',
          columns: [{ name: 'email' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxEmail',
        },
        {
          name: 'idx_phone',
          columns: [{ name: 'phone' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxPhone',
        },
        {
          name: 'idx_create_time',
          columns: [{ name: 'create_time' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxCreateTime',
        },
      ],
    },
    {
      id: 'log_table',
      name: 'db.tplLogName',
      description: 'db.tplLogDesc',
      category: 'log',
      tags: ['db.tplTagLog', 'db.tplTagAudit', 'db.tplTagMonitor'],
      usageCount: 0,
      createdAt: Date.now(),
      columns: [
        {
          name: 'id',
          type: 'bigint',
          length: '20',
          notNull: true,
          isPrimaryKey: true,
          autoIncrement: true,
          comment: 'db.tplColPriId',
        },
        {
          name: 'log_type',
          type: 'varchar',
          length: '50',
          notNull: true,
          comment: 'db.tplColLogType',
        },
        {
          name: 'log_level',
          type: 'varchar',
          length: '20',
          notNull: true,
          defaultValue: 'INFO',
          comment: 'db.tplColLogLevel',
        },
        {
          name: 'title',
          type: 'varchar',
          length: '200',
          notNull: false,
          comment: 'db.tplColLogTitle',
        },
        {
          name: 'message',
          type: 'text',
          notNull: true,
          comment: 'db.tplColLogMsg',
        },
        {
          name: 'context',
          type: 'json',
          notNull: false,
          comment: 'db.tplColContext',
        },
        {
          name: 'user_id',
          type: 'bigint',
          length: '20',
          notNull: false,
          comment: 'db.tplColUserId',
        },
        {
          name: 'user_name',
          type: 'varchar',
          length: '100',
          notNull: false,
          comment: 'db.tplColUsername',
        },
        {
          name: 'ip_address',
          type: 'varchar',
          length: '50',
          notNull: false,
          comment: 'db.tplColIp',
        },
        {
          name: 'user_agent',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColUserAgent',
        },
        {
          name: 'request_url',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColReqUrl',
        },
        {
          name: 'request_method',
          type: 'varchar',
          length: '10',
          notNull: false,
          comment: 'db.tplColReqMethod',
        },
        {
          name: 'request_params',
          type: 'text',
          notNull: false,
          comment: 'db.tplColReqParams',
        },
        {
          name: 'response_code',
          type: 'int',
          length: '11',
          notNull: false,
          comment: 'db.tplColRespCode',
        },
        {
          name: 'duration',
          type: 'int',
          length: '11',
          notNull: false,
          comment: 'db.tplColDuration',
        },
        {
          name: 'create_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColCreateTime',
        },
      ],
      indexes: [
        {
          name: 'idx_log_type',
          columns: [{ name: 'log_type' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxLogType',
        },
        {
          name: 'idx_log_level',
          columns: [{ name: 'log_level' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxLogLevel',
        },
        {
          name: 'idx_create_time',
          columns: [{ name: 'create_time' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxCreateTime',
        },
        {
          name: 'idx_user_id',
          columns: [{ name: 'user_id' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxUserId',
        },
      ],
    },
    {
      id: 'config_table',
      name: 'db.tplConfigName',
      description: 'db.tplConfigDesc',
      category: 'config',
      tags: ['db.tplTagConfig', 'db.tplTagSystem', 'db.tplTagSetting'],
      usageCount: 0,
      createdAt: Date.now(),
      columns: [
        {
          name: 'id',
          type: 'bigint',
          length: '20',
          notNull: true,
          isPrimaryKey: true,
          autoIncrement: true,
          comment: 'db.tplColPriId',
        },
        {
          name: 'config_key',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColConfigKey',
        },
        {
          name: 'config_value',
          type: 'text',
          notNull: false,
          comment: 'db.tplColConfigValue',
        },
        {
          name: 'config_type',
          type: 'varchar',
          length: '20',
          notNull: true,
          defaultValue: 'string',
          comment: 'db.tplColValueType',
        },
        {
          name: 'config_group',
          type: 'varchar',
          length: '50',
          notNull: false,
          comment: 'db.tplColConfigGroup',
        },
        {
          name: 'description',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColConfigDesc',
        },
        {
          name: 'is_system',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '0',
          comment: 'db.tplColIsSystem',
        },
        {
          name: 'is_editable',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '1',
          comment: 'db.tplColIsEditable',
        },
        {
          name: 'sort_order',
          type: 'int',
          length: '11',
          notNull: true,
          defaultValue: '0',
          comment: 'db.tplColSort',
        },
        {
          name: 'creator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColCreatorId',
        },
        {
          name: 'creator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColCreator',
        },
        {
          name: 'create_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColCreateTime',
        },
        {
          name: 'updator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColUpdatorId',
        },
        {
          name: 'updator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColUpdator',
        },
        {
          name: 'update_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColUpdateTime',
        },
      ],
      indexes: [
        {
          name: 'uk_config_key',
          columns: [{ name: 'config_key' }],
          unique: true,
          type: 'BTREE',
          comment: 'db.tplIdxConfigKeyUnique',
        },
        {
          name: 'idx_config_group',
          columns: [{ name: 'config_group' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxConfigGroup',
        },
      ],
    },
    {
      id: 'dictionary_table',
      name: 'db.tplDictName',
      description: 'db.tplDictDesc',
      category: 'dictionary',
      tags: ['db.tplTagDict', 'db.tplTagBasic', 'db.tplTagSystem'],
      usageCount: 0,
      createdAt: Date.now(),
      columns: [
        {
          name: 'id',
          type: 'bigint',
          length: '20',
          notNull: true,
          isPrimaryKey: true,
          autoIncrement: true,
          comment: 'db.tplColPriId',
        },
        {
          name: 'dict_type',
          type: 'varchar',
          length: '50',
          notNull: true,
          comment: 'db.tplColDictType',
        },
        {
          name: 'dict_code',
          type: 'varchar',
          length: '50',
          notNull: true,
          comment: 'db.tplColDictCode',
        },
        {
          name: 'dict_label',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColDictLabel',
        },
        {
          name: 'dict_value',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColDictValue',
        },
        {
          name: 'parent_id',
          type: 'bigint',
          length: '20',
          notNull: false,
          defaultValue: '0',
          comment: 'db.tplColParentId',
        },
        {
          name: 'level',
          type: 'int',
          length: '11',
          notNull: true,
          defaultValue: '1',
          comment: 'db.tplColLevel',
        },
        {
          name: 'sort_order',
          type: 'int',
          length: '11',
          notNull: true,
          defaultValue: '0',
          comment: 'db.tplColSort',
        },
        {
          name: 'css_class',
          type: 'varchar',
          length: '50',
          notNull: false,
          comment: 'db.tplColCssClass',
        },
        {
          name: 'list_class',
          type: 'varchar',
          length: '50',
          notNull: false,
          comment: 'db.tplColListClass',
        },
        {
          name: 'is_default',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '0',
          comment: 'db.tplColIsDefault',
        },
        {
          name: 'status',
          type: 'tinyint',
          length: '1',
          notNull: true,
          defaultValue: '1',
          comment: 'db.tplColStatus',
        },
        {
          name: 'remark',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColRemark',
        },
        {
          name: 'creator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColCreatorId',
        },
        {
          name: 'creator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColCreator',
        },
        {
          name: 'create_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColCreateTime',
        },
        {
          name: 'updator_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColUpdatorId',
        },
        {
          name: 'updator',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColUpdator',
        },
        {
          name: 'update_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColUpdateTime',
        },
      ],
      indexes: [
        {
          name: 'uk_dict_type_code',
          columns: [{ name: 'dict_type' }, { name: 'dict_code' }],
          unique: true,
          type: 'BTREE',
          comment: 'db.tplIdxDictTypeCodeUnique',
        },
        {
          name: 'idx_dict_type',
          columns: [{ name: 'dict_type' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxDictType',
        },
        {
          name: 'idx_parent_id',
          columns: [{ name: 'parent_id' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxParentId',
        },
      ],
    },
    {
      id: 'audit_table',
      name: 'db.tplAuditName',
      description: 'db.tplAuditDesc',
      category: 'log',
      tags: ['db.tplTagAudit', 'db.tplTagMonitor', 'db.tplTagSystem'],
      usageCount: 0,
      createdAt: Date.now(),
      columns: [
        {
          name: 'id',
          type: 'bigint',
          length: '20',
          notNull: true,
          isPrimaryKey: true,
          autoIncrement: true,
          comment: 'db.tplColPriId',
        },
        {
          name: 'table_name',
          type: 'varchar',
          length: '100',
          notNull: true,
          comment: 'db.tplColTableName',
        },
        {
          name: 'record_id',
          type: 'bigint',
          length: '20',
          notNull: true,
          comment: 'db.tplColRecordId',
        },
        {
          name: 'action',
          type: 'varchar',
          length: '20',
          notNull: true,
          comment: 'db.tplColAction',
        },
        {
          name: 'old_values',
          type: 'json',
          notNull: false,
          comment: 'db.tplColOldValues',
        },
        {
          name: 'new_values',
          type: 'json',
          notNull: false,
          comment: 'db.tplColNewValues',
        },
        {
          name: 'changed_fields',
          type: 'varchar',
          length: '500',
          notNull: false,
          comment: 'db.tplColChangedFields',
        },
        {
          name: 'user_id',
          type: 'bigint',
          length: '20',
          notNull: false,
          comment: 'db.tplColUserId',
        },
        {
          name: 'user_name',
          type: 'varchar',
          length: '100',
          notNull: false,
          comment: 'db.tplColUsername',
        },
        {
          name: 'ip_address',
          type: 'varchar',
          length: '50',
          notNull: false,
          comment: 'db.tplColIp',
        },
        {
          name: 'create_time',
          type: 'datetime',
          notNull: true,
          defaultValue: 'CURRENT_TIMESTAMP',
          comment: 'db.tplColCreateTime',
        },
      ],
      indexes: [
        {
          name: 'idx_table_record',
          columns: [{ name: 'table_name' }, { name: 'record_id' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxTableRecord',
        },
        {
          name: 'idx_action',
          columns: [{ name: 'action' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxAction',
        },
        {
          name: 'idx_user_id',
          columns: [{ name: 'user_id' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxUserId',
        },
        {
          name: 'idx_create_time',
          columns: [{ name: 'create_time' }],
          unique: false,
          type: 'BTREE',
          comment: 'db.tplIdxCreateTime',
        },
      ],
    },
  ];
