import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import vuePlugin from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';

export default [
    {
        ignores: [
            '*.sh',
            'node_modules',
            'lib',
            '*.md',
            '*.scss',
            '*.woff',
            '*.ttf',
            '.vscode',
            '.idea',
            'dist',
            'mock',
            'public',
            'bin',
            'build',
            'config',
            'index.html',
            'src/assets',
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    ...vuePlugin.configs['flat/recommended'],
    {
        files: ['**/*.{js,ts,tsx,vue}'],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            parser: vueParser,
            parserOptions: {
                parser: tseslint.parser,
            },
            globals: {
                browser: true,
                es2021: true,
                node: true,
                console: true,
                window: true,
                document: true,
                setTimeout: true,
            },
        },
        plugins: {
            vue: vuePlugin,
        },
        rules: {
            '@typescript-eslint/ban-ts-ignore': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-var-requires': 'off',
            '@typescript-eslint/no-empty-function': 'off',
            '@typescript-eslint/no-use-before-define': 'off',
            '@typescript-eslint/ban-ts-comment': 'off',
            '@typescript-eslint/ban-types': 'off',
            '@typescript-eslint/no-non-null-assertion': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
            '@typescript-eslint/no-unused-vars': 'off',
            '@typescript-eslint/no-unused-expressions': 'off',
            '@typescript-eslint/no-this-alias': 'off',
            '@typescript-eslint/no-wrapper-object-types': 'off',

            // Vue rules
            // shallowOnly：仅拦截「prop 本身被重新赋值」（破坏单向数据流），
            // 放行受控深层写入（如 auto-form 对共享引用 form 的字段级 v-model 绑定，设计如此）
            'vue/no-mutating-props': ['error', { shallowOnly: true }],
            'vue/html-indent': 'off',
            'vue/script-indent': 'off',
            'vue/custom-event-name-casing': 'off',
            'vue/attributes-order': 'off',
            'vue/one-component-per-file': 'off',
            'vue/html-closing-bracket-newline': 'off',
            'vue/max-attributes-per-line': 'off',
            'vue/multiline-html-element-content-newline': 'off',
            'vue/singleline-html-element-content-newline': 'off',
            'vue/attribute-hyphenation': 'off',
            'vue/html-self-closing': 'off',
            'vue/no-multiple-template-root': 'off',
            'vue/require-default-prop': 'off',
            'vue/no-v-model-argument': 'off',
            'vue/no-arrow-functions-in-watch': 'off',
            'vue/no-template-key': 'off',
            'vue/no-v-html': 'off',
            'vue/no-unused-vars': 'off',
            'vue/comment-directive': 'off',
            'vue/no-parsing-error': 'off',
            'vue/no-deprecated-v-on-native-modifier': 'off',
            'vue/multi-word-component-names': 'off',
            'vue/require-prop-types': 'off',
            'vue/no-template-shadow': 'off',
            'vue/v-on-event-hyphenation': 'off',
            'vue/no-required-prop-with-default': 'off',
            'vue/html-closing-bracket-spacing': 'off',
            'vue/require-valid-default-prop': 'off',
            'vue/no-side-effects-in-computed-properties': 'off',
            'vue/component-definition-name-casing': 'off',
            'vue/v-slot-style': 'off',
            'vue/valid-v-for': 'off',
            'vue/valid-template-root': 'off',
            'vue/v-bind-style': 'off',
            'vue/no-ref-as-operand': 'off',
            'vue/no-dupe-keys': 'off',

            // JavaScript rules
            'no-useless-escape': 'off',
            'no-sparse-arrays': 'off',
            'no-prototype-builtins': 'off',
            'no-constant-condition': 'off',
            'no-use-before-define': 'off',
            'no-restricted-globals': 'off',
            'no-restricted-syntax': 'off',
            'generator-star-spacing': 'off',
            'no-unreachable': 'off',
            'no-unused-vars': 'off',
            'no-case-declarations': 'off',
            'no-redeclare': 'off',
            'no-undef': 'off',
            'prefer-const': 'off',
            'no-var': 'off',
            'no-useless-assignment': 'off',
            'no-constant-binary-expression': 'off',
            'no-empty': 'off',
            'no-irregular-whitespace': 'off',
            'no-fallthrough': 'off',
            '@typescript-eslint/no-array-constructor': 'off',
            '@typescript-eslint/no-unsafe-function-type': 'off',
            '@typescript-eslint/no-empty-object-type': 'off',
            '@typescript-eslint/no-empty-interface': 'off',
            'preserve-caught-error': 'off',
        },
    },
];
