version: '3'
services:

  mayfly-mysql:
    image: mysql:5.7
    container_name: mayfly-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: mayfly-go
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3366:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
