package imsg

import "mayfly-go/pkg/i18n"

// Zh_CN Mongo 模块中文文案
var Zh_CN = map[i18n.MsgId]string{
	LogMongoSave:             "Mongo-保存",
	LogMongoDelete:           "Mongo-删除",
	LogMongoRunCmd:           "Mongo-执行命令",
	LogUpdateDocs:            "Mongo-更新文档",
	LogDelDocs:               "Mongo-删除文档",
	LogInsertDocs:            "Mongo-插入文档",
	LogMongoQueryDocs:        "Mongo-查询文档",
	LogMongoCreateCollection: "Mongo-创建集合",
	LogMongoDropCollection:   "Mongo-删除集合",
	LogMongoDropDatabase:     "Mongo-删除数据库",
	LogMongoCreateIndex:      "Mongo-创建索引",
	LogMongoDropIndex:        "Mongo-删除索引",
	LogMongoBatchUpdate:      "Mongo-批量更新",
	LogMongoBatchDelete:      "Mongo-批量删除",
	LogMongoExport:           "Mongo-导出文档",
	LogMongoAggregate:        "Mongo-聚合查询",

	ErrMongoInfoExist:               "该连接信息已存在",
	ErrMongoNotFound:                "Mongo实例不存在",
	ErrMongoInvalidId:               "Mongo实例ID不合法",
	ErrMongoDatabaseEmpty:           "数据库名称不能为空",
	ErrMongoCollectionEmpty:         "集合名称不能为空",
	ErrMongoUriRequired:             "连接URI不能为空",
	ErrMongoConnFailed:              "Mongo连接失败：{{.detail}}",
	ErrMongoDocsEmpty:               "文档内容不能为空",
	ErrMongoUpdateOperatorForbidden: "文档字段名不能以 $ 开头；更新指令由服务端根据提交内容生成",
	ErrMongoJsonInvalid:             "{{.field}} 无法解析为JSON文档：{{.detail}}。注意：JSON的key必须使用双引号",
	ErrMongoCommandEmpty:            "命令内容不能为空",
	ErrMongoCmdPermDenied:           "命令 {{.command}} 属于「{{.level}}」级别，需要权限「{{.permission}}」",
	ErrMongoIdTokenInvalid:          "文档主键令牌不合法或已被篡改",
	ErrMongoIdTokenMissing:          "该文档缺少 _id 主键（可能已在投影中排除），无法定位文档",
	ErrMongoConfirmMismatch:         "确认名称不一致，请输入「{{.expect}}」以继续",
	ErrMongoExecFailed:              "Mongo操作执行失败：{{.detail}}",
	ErrMongoExecTimeout:             "Mongo操作超过 {{.limit}} 秒已取消，请收窄查询条件或为相关字段建立索引",
	ErrMongoDocNotMatched:           "没有匹配到文档，主键可能已变更或文档已被删除",
	ErrMongoDocConflict:             "该文档已被其他人修改，本次写入已取消；请刷新后重新编辑",
	ErrMongoUnauthorized:            "该实例需要认证：连接串没有可用凭证，或当前账号缺少该操作权限（{{.detail}}）。请在实例编辑里补全账号密码与 authSource",
	ErrMongoPipelineInvalid:         "聚合管道必须是非空的 stage 数组，如 [{\"$match\":{...}}]",
	ErrMongoIndexSpecsInvalid:       "索引定义必须是非空数组，且每项含 key 字段，如 [{\"key\":{\"a\":1},\"name\":\"a_1\"}]",
	ErrMongoBatchCountMismatch:      "命中数已变化：预期 {{.expect}} 条，实际 {{.actual}} 条，本次操作未执行，请重新确认",
	ErrMongoFormatUnsupported:       "不支持的导出格式 {{.format}}，当前支持 {{.supported}}",

	LevelReadName:       "只读",
	LevelDataSaveName:   "写数据",
	LevelDataDelName:    "删数据",
	LevelStructSaveName: "结构变更",
	LevelStructDelName:  "结构销毁",
	LevelAdminName:      "服务器管理",
}
